### ISSUE TITLE
go.mod 不和main.go在一起感觉很怪

### ISSUE THREAD

**Issue by aircjm** [Jansora/pancake#1]
go.mod 不和main.go在一起感觉很怪,我改成这样可以吗？？

![image](https://user-images.githubusercontent.com/18283183/87410360-ca035a00-c5f8-11ea-97be-2a9256b75dc5.png)

**Comment by Jansora** [comment]
可以哦,  这是我第一次写Golang 代码, 所以代码不是很规范, 感谢提意见.
